
server:
  port: 8080

spring:
  application:
    name: deal-pipeline-management

  data:
    mongodb:
      uri: mongodb://localhost:27017/deal_pipeline_db

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.springframework.security: INFO

jwt:
  secret: my-super-secret-key-for-investment-banking-deal-pipeline
  expiration: 86400000   # 1 day

